# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20150512_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='track_display_set', to='music.Artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(null=True, to='music.Artist'),
        ),
    ]
