# Generated by Django 2.0.1 on 2018-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20160213_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='path',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='path',
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='lastplayed',
            name='file_path',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='file_path',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='path',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
