# Generated by Django 2.1 on 2019-01-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20160213_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='musicbrainz_albumid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='musicbrainz_releasegroupid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='musicbrainz_artistid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='musicbrainz_trackid',
            field=models.UUIDField(null=True),
        ),
    ]
