# Generated by Django 2.1.5 on 2019-01-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20160213_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(to='music.Artist'),
        ),
    ]
