# Generated by Django 2.1 on 2019-02-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190129_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artists',
            field=models.ManyToManyField(to='music.Artist'),
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('collection', 'path'), ('collection', 'name', 'musicbrainz_artistid')},
        ),
    ]
