# Generated by Django 4.0 on 2022-01-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20150512_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
